pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:rickatfw/sandbox-cli.git
          - cd sandbox-cli.git
          - git push --mirror git@github.com:rherrick/sandbox-cli.git

